# Generated by Django 5.1 on 2025-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
